language: php

sudo: false

php:
  - 5.3
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS="" && phpenv config-rm xdebug.ini; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - vendor/bin/phpunit -v $PHPUNIT_FLAGS

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php vendor/bin/coveralls -v; fi
